### PR TITLE
Added Burkina Faso to Canada in English

### PR DESCRIPTION
**Pull request by kbernou**
I've added 5 countries to the English JSON file.

### CODE REVIEW

**Comment by xaca** [comment]
@kbernou Thanks for you help. Could you add enlgish and spanish name, of each contry. 🙏

**Comment by kbernou** [comment]
Sure thing, I'll get that done shortly.

**Comment by kbernou** [comment]
@xaca I'm sorry, I think I'm missing something. Where should the translation of the country names be put?

**Comment by xaca** [comment]
> @xaca I'm sorry, I think I'm missing something. Where should the translation of the country names be put?

I don't know, looking in your solution right now.

**Comment by xaca** [comment]
@kbernou  Could be something like :

` name:{en:Spain,es:España}`

**Pull request merged**
